services:
  postgres:
    container_name: spa_db
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - spa_intentions:/var/lib/postgresdata
    environment:
      POSTGRES_DB: spa_intentions
      POSTGRES_USER: spa
      POSTGRES_PASSWORD: spa
  laravel:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spa_web
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=spa_intentions
      - DB_USERNAME=spa
      - DB_PASSWORD=spa
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
    ports:
      - '8000:8000'
      - '5173:5173'
    depends_on:
      - postgres
volumes:
  spa_intentions: