services:
  postgres:
    container_name: spa_db
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - spa_intentions:/var/lib/postgresdata
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  laravel:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spa_web
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - VITE_PORT=${VITE_PORT}
    volumes:
      - .:/var/www/html
    ports:
      - '8000:8000'
      - '5173:5173'
    depends_on:
      - postgres
volumes:
  spa_intentions: